name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       # configuration: [Debug, Release]
  #       configuration: [Release]
  #       os: [windows-latest, macos-latest, ubuntu-latest]
  #       #os: [windows-latest]
  build-windows:
    runs-on: windows-latest
    env:
      Solution_Name: NameSorter.sln
      Test_Project_Path: TestNameSorter/TestNameSorter.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    # Execute all unit tests in the solution
    - name: Run Unit Tests
      run: dotnet test ${{ env.Test_Project_Path }}
    # Build Console App
    - name: Build Console App
      run: dotnet build --configuration Release ${{ env.Solution_Name }}
    
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifact
        path: ./NameSorter/bin/Release/net8.0/
    
  # deploy:
  #   needs: [build-windows]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: windows-artifact

  #   - name: Deploy to Releases
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: |
  #         ./NameSorter/bin/Release/net8.0/*
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       api_key: ${{ secrets.GITHUB_TOKEN }}
  #       tag_name: ${{ github.run_number }}
  #       release_name: Release ${{ github.ref }}
  #       body: New Release.
  #       draft: true
  #       prerelease: true
